### ISSUE TITLE
Fails on 3490

### ISSUE THREAD

**Issue by tomchiverton** [SourceDoctor/cacti-plugins#1]
Traceback (most recent call last):
  File "./fritzbox.py", line 143, in <module>
    output = run()
  File "./fritzbox.py", line 130, in run
    ret = fc.wan_information
  File "./fritzbox.py", line 103, in wan_information
    return self.fetch(service, action)
  File "./fritzbox.py", line 46, in fetch
    ret = self.get_data(service, a)
  File "./fritzbox.py", line 29, in get_data
    return self.fc.call_action(service, action)
  File "/usr/lib/python2.7/site-packages/fritzconnection/fritzconnection.py", line 406, in call_action
    return action.execute(**kwargs)
  File "/usr/lib/python2.7/site-packages/fritzconnection/fritzconnection.py", line 130, in execute
    result = self.parse_response(response.content)
  File "/usr/lib/python2.7/site-packages/fritzconnection/fritzconnection.py", line 142, in parse_response
    root = etree.fromstring(response)
  File "src/lxml/etree.pyx", line 3230, in lxml.etree.fromstring (src/lxml/etree.c:81070)
  File "src/lxml/parser.pxi", line 1871, in lxml.etree._parseMemoryDocument (src/lxml/etree.c:121250)
  File "src/lxml/parser.pxi", line 1759, in lxml.etree._parseDoc (src/lxml/etree.c:119926)
  File "src/lxml/parser.pxi", line 1125, in lxml.etree._BaseParser._parseDoc (src/lxml/etree.c:114173)
  File "src/lxml/parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/etree.c:107738)
  File "src/lxml/parser.pxi", line 709, in lxml.etree._handleParseResult (src/lxml/etree.c:109447)
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError (src/lxml/etree.c:108301)
  File "<string>", line 1
lxml.etree.XMLSyntaxError: Opening and ending tag mismatch: HR line 1 and BODY, line 1, column 162

**Comment by SourceDoctor** [comment]
all modules installed? 
request
lxml
fritzconnection 

Fritzbox allows UPNP Connection?

**Comment by tomchiverton** [comment]
Suddenly started working as I was testing !

Pip details below and home network>network>network settings>"Transmit status information over UPnP" ticked.

```
# pip install request lxml fritzconnection
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip install --user` instead.
Requirement already satisfied: request in /usr/lib/python2.7/site-packages
Requirement already satisfied: lxml in /usr/lib64/python2.7/site-packages
Requirement already satisfied: fritzconnection in /usr/lib/python2.7/site-packages
Requirement already satisfied: get in /usr/lib/python2.7/site-packages (from request)
Requirement already satisfied: post in /usr/lib/python2.7/site-packages (from request)
Requirement already satisfied: setuptools in /usr/lib/python2.7/site-packages (from request)
Requirement already satisfied: requests>=2.2.0 in /usr/lib/python2.7/site-packages (from fritzconnection)
Requirement already satisfied: query_string in /usr/lib/python2.7/site-packages (from get->request)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python2.7/site-packages (from requests>=2.2.0->fritzconnection)
Requirement already satisfied: idna<2.7,>=2.5 in /usr/lib/python2.7/site-packages (from requests>=2.2.0->fritzconnection)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/lib/python2.7/site-packages (from requests>=2.2.0->fritzconnection)
Requirement already satisfied: public in /usr/lib/python2.7/site-packages (from query_string->get->request)
```

**Comment by SourceDoctor** [comment]
which fritzbox do you use?
in general it Looks for me as a problem with Connection to fritzbox, or with fritzconnection module

**Comment by tomchiverton** [comment]
Ah ha. Found the oddness. With uPnP on and app. access off "traffic" works but "dslinfo" says

```
Traceback (most recent call last):
  File "./fritzbox.py", line 143, in <module>
    output = run()
  File "./fritzbox.py", line 128, in run
    ret = fc.dsl_information
  File "./fritzbox.py", line 90, in dsl_information
    return self.fetch(service, action, keys)
  File "./fritzbox.py", line 46, in fetch
    ret = self.get_data(service, a)
  File "./fritzbox.py", line 29, in get_data
    return self.fc.call_action(service, action)
  File "/usr/lib/python2.7/site-packages/fritzconnection/fritzconnection.py", line 405, in call_action
    action = self._get_action(service_name, action_name)
  File "/usr/lib/python2.7/site-packages/fritzconnection/fritzconnection.py", line 378, in _get_action
    raise ServiceError('Unknown Service: ' + service_name)
fritzconnection.fritzconnection.ServiceError: Unknown Service: WANDSLInterfaceConfig:1
```

turning on app access neither works as above.

**Comment by SourceDoctor** [comment]
ok, so your Problem is solved?

**Comment by tomchiverton** [comment]
dslinfo does not work, traffic does

**Comment by SourceDoctor** [comment]
dslinfo runs over the same class, so it should run also
